package fr.exratio.jme.devkit.properties.component.integer;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import fr.exratio.jme.devkit.properties.component.AbstractPropertyEditor;
import fr.exratio.jme.devkit.properties.component.IntegerFormatFactory;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;

public class IntegerEditor extends AbstractPropertyEditor<Integer> {

  public static final String LISTENED_PROPERTY_NAME = "value";

  private JFormattedTextField valueTextField;
  private JPanel contentPanel;

  public IntegerEditor() {
    this(0);
  }

  public IntegerEditor(Integer value) {
    super(value);
    $$$setupUI$$$();
  }

  @Override
  public void setTypedValue(Integer newValue) {
    if (newValue == null) {
      newValue = 0;
    }
    this.valueTextField.setValue(newValue);
    super.setTypedValue(newValue);
  }

  protected Integer computeValue() {
    return ((Number) valueTextField.getValue()).intValue();
  }


  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    contentPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    contentPanel.add(valueTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST,
        GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
  }


  public JComponent $$$getRootComponent$$$() {
    return contentPanel;
  }


  private void createUIComponents() {
    contentPanel = this;
    valueTextField = new JFormattedTextField(new IntegerFormatFactory(), value);
    valueTextField.addPropertyChangeListener(LISTENED_PROPERTY_NAME, propertyChangeListener);
  }
}
