title = My JME Project
sdkConfig {
  theme = com.github.weisj.darklaf.theme.DarculaTheme
  defaultMaterial = Common/MatDefs/Light/PBRLighting.j3md
  showCamRotationWidget = true
  showDebugLightsWindow = false
  showRunAppStateWindow = false
}
mainSize {
  width = 800
  height = 600
}
location {
  x = 0
  y = 0
}
project {
  assetDirectory = /Users/quentinr/Projects/jme-swing-devkit/src/main/resources
}
camera {
  viewport {
    color {
      r = 0.5
      g = 0.6
      b = 0.7
      a = 1.0
    }
  }
  fieldOfView = 45.0
  frustum {
    near = 0.1
    far = 1000.0
  }
  dimension {
    width = 600.0
    height = 480.0
  }

}
grid {
  show = true
  size {
    x = 200.0
    y = 200.0
    z = 1.0
  }
  color {
    r = 0.75
    g = 0.75
    b = 0.75
    a = 1.0
  }
  location {
    x = -100.0
    y = 0.0
    z = -100.0
  }
}
