package fr.exratio.jme.devkit.forms;

import fr.exratio.jme.devkit.swing.JSplitPaneWithZeroSizeDivider;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import org.jdesktop.swingx.JXLabel;

public class MainPage {

  public static String WINDOW_ID = "main";
  private final JFrame frame;

  private JPanel rootPanel;
  private JPanel southPanel;
  private JPanel eastPanel;
  private JPanel centerPanel;
  private JPanel westPanel;
  private JTabbedPane centerTabbedPane;
  private JTabbedPane westTabbedPane;
  private JTabbedPane southTabbedPane;
  private JSplitPane rightSplitPane;
  private JSplitPane leftSplitPane;
  private JSplitPane verticalSplitPane;
  private JScrollPane eastArea;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  public MainPage(JFrame frame) {
    this.frame = frame;
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    rootPanel = new JPanel();
    rootPanel.setLayout(new BorderLayout(0, 0));
    final JLabel label1 = new JLabel();
    label1.setText("WEST");
    rootPanel.add(label1, BorderLayout.WEST);
    final JLabel label2 = new JLabel();
    label2.setText("SOUTH");
    rootPanel.add(label2, BorderLayout.SOUTH);
    final JLabel label3 = new JLabel();
    label3.setText("EAST");
    rootPanel.add(label3, BorderLayout.EAST);
    verticalSplitPane.setContinuousLayout(true);
    verticalSplitPane.setOneTouchExpandable(true);
    verticalSplitPane.setOrientation(0);
    rootPanel.add(verticalSplitPane, BorderLayout.CENTER);
    leftSplitPane.setContinuousLayout(true);
    leftSplitPane.setOneTouchExpandable(true);
    verticalSplitPane.setLeftComponent(leftSplitPane);
    rightSplitPane.setOneTouchExpandable(true);
    leftSplitPane.setRightComponent(rightSplitPane);
    eastPanel = new JPanel();
    eastPanel.setLayout(new BorderLayout(0, 0));
    eastPanel.setMinimumSize(new Dimension(100, 50));
    eastPanel.setPreferredSize(new Dimension(200, 500));
    rightSplitPane.setRightComponent(eastPanel);
    eastArea = new JScrollPane();
    eastArea.setMaximumSize(new Dimension(-1, -1));
    eastArea.setMinimumSize(new Dimension(0, 0));
    eastPanel.add(eastArea, BorderLayout.CENTER);
    centerPanel.setLayout(new BorderLayout(0, 0));
    centerPanel.setMinimumSize(new Dimension(300, 300));
    centerPanel.setPreferredSize(new Dimension(600, 480));
    rightSplitPane.setLeftComponent(centerPanel);
    centerTabbedPane = new JTabbedPane();
    centerPanel.add(centerTabbedPane, BorderLayout.CENTER);
    westPanel = new JPanel();
    westPanel.setLayout(new BorderLayout(0, 0));
    westPanel.setMinimumSize(new Dimension(100, 300));
    westPanel.setPreferredSize(new Dimension(200, 500));
    leftSplitPane.setLeftComponent(westPanel);
    westTabbedPane = new JTabbedPane();
    westTabbedPane.setMinimumSize(new Dimension(200, 300));
    westTabbedPane.setPreferredSize(new Dimension(200, 300));
    westTabbedPane.setTabPlacement(2);
    westPanel.add(westTabbedPane, BorderLayout.CENTER);
    southPanel = new JPanel();
    southPanel.setLayout(new BorderLayout(0, 0));
    southPanel.setMinimumSize(new Dimension(500, 10));
    southPanel.setPreferredSize(new Dimension(500, 300));
    verticalSplitPane.setRightComponent(southPanel);
    southTabbedPane = new JTabbedPane();
    southPanel.add(southTabbedPane, BorderLayout.CENTER);
  }


  public JComponent $$$getRootComponent$$$() {
    return rootPanel;
  }

  private void createUIComponents() {
    rightSplitPane = new JSplitPaneWithZeroSizeDivider(JSplitPane.HORIZONTAL_SPLIT);
    leftSplitPane = new JSplitPaneWithZeroSizeDivider(JSplitPane.HORIZONTAL_SPLIT);
    verticalSplitPane = new JSplitPaneWithZeroSizeDivider(JSplitPane.VERTICAL_SPLIT);
    centerPanel = new JPanel(new BorderLayout());
    centerPanel.addComponentListener(new ComponentAdapter() {
      @Override
      public void componentResized(ComponentEvent e) {
        frame.revalidate();
      }
    });

  }

  public void addTabToWestPane(String title, Component content) {
    westTabbedPane.addTab(title, content);
    int tabIndex = westTabbedPane.indexOfTab(title);
    JXLabel tabLabel = new JXLabel(title);
    tabLabel.setTextRotation(3 * Math.PI / 2);
    westTabbedPane.setTabComponentAt(tabIndex, tabLabel);
    //frame.repaint();
  }

  public void addTabToSouthPane(String title, Component content) {
    southTabbedPane.addTab(title, content);
    //mainFrame.repaint();
  }

  public void addTabToCenterPane(String title, Component content) {
    centerTabbedPane.addTab(title, content);
    //mainFrame.repaint();
  }

  public void addTabToCenterPane(String title, Component content, Icon icon) {
    centerTabbedPane.addTab(title, icon, content);
    //mainFrame.repaint();
  }

  public void setEastArea(Component component) {
    eastArea.setViewportView(component);
  }
}
