package fr.exratio.jme.devkit.forms;

import com.google.common.collect.ImmutableList;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jme3.asset.ModelKey;
import fr.exratio.jme.devkit.action.RemoveLinkedAssetAction;
import fr.exratio.jme.devkit.registration.spatial.AssetLinkNodeRegistrar.AssetLinkNodeTreeNode;
import fr.exratio.jme.devkit.service.EditorJmeApplication;
import fr.exratio.jme.devkit.service.SceneGraphService;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class RemoveLinkedAsset extends JPanel {

  private JPanel rootPanel;

  // JFormDesigner - Variables declaration - DO NOT MODIFY  //GEN-BEGIN:variables
  // Generated using JFormDesigner Evaluation license - Quentin Raphaneau
  private JList modelKeysList;
  private JButton removeLinkedAssetsButton;

  @Autowired
  public RemoveLinkedAsset(
      RemoveLinkedAssetAction removeLinkedAssetAction,
      EditorJmeApplication editorJmeApplication,
      SceneGraphService sceneGraphService) {
    initComponents();

    editorJmeApplication.enqueue(() -> {
      final ImmutableList<ModelKey> modelKeys = ImmutableList
          .copyOf(((AssetLinkNodeTreeNode) sceneGraphService
              .getSelectedObject()).getUserObject().getAssetLoaderKeys());
      SwingUtilities.invokeLater(() -> {
        DefaultListModel<ModelKey> listModel = new DefaultListModel<>();

        for (ModelKey key : modelKeys) {
          listModel.addElement(key);
        }

        modelKeysList.setModel(listModel);
      });

    });

    removeLinkedAssetsButton.setAction(removeLinkedAssetAction);

  }

  private void initComponents() {
    // JFormDesigner - Component initialization - DO NOT MODIFY  //GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Quentin Raphaneau
    var scrollPane1 = new JScrollPane();
    modelKeysList = new JList();
    removeLinkedAssetsButton = new JButton();

    //======== this ========
    setBorder(new CompoundBorder(new TitledBorder(new
        EmptyBorder(0, 0, 0, 0), "JFor\u006dDesi\u0067ner \u0045valu\u0061tion",
        TitledBorder.CENTER, TitledBorder.BOTTOM, new Font("Dia\u006cog", Font.BOLD, 12),
        Color.red), getBorder()));
    addPropertyChangeListener(e -> {
      if ("bord\u0065r".equals(e.getPropertyName())) {
        throw new RuntimeException();
      }
    });
    setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));

    //======== scrollPane1 ========
    {
      scrollPane1.setViewportView(modelKeysList);
    }
    add(scrollPane1, new GridConstraints(0, 0, 1, 1,
        GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW
            | GridConstraints.SIZEPOLICY_WANT_GROW,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW
            | GridConstraints.SIZEPOLICY_WANT_GROW,
        null, null, null));

    //---- removeLinkedAssetsButton ----
    removeLinkedAssetsButton.setText("Remove Selected Linked Assets");
    add(removeLinkedAssetsButton, new GridConstraints(1, 0, 1, 1,
        GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
        GridConstraints.SIZEPOLICY_FIXED,
        null, null, null));
    // JFormDesigner - End of component initialization  //GEN-END:initComponents
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    rootPanel = new JPanel();
    rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
    final JScrollPane scrollPane1 = new JScrollPane();
    rootPanel.add(scrollPane1,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null,
            null, null, 0, false));
    modelKeysList = new JList();
    scrollPane1.setViewportView(modelKeysList);
    removeLinkedAssetsButton = new JButton();
    removeLinkedAssetsButton.setText("Remove Selected Linked Assets");
    rootPanel.add(removeLinkedAssetsButton,
        new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return rootPanel;
  }

  // JFormDesigner - End of variables declaration  //GEN-END:variables
}
