package com.jayfella.devkit.properties.component;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jayfella.devkit.core.ColorConverter;
import com.jme3.math.ColorRGBA;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.PropertyChangeListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.border.TitledBorder;

public class ColorRGBAComponent extends JMEDevKitComponentSwingView<ColorRGBA> {

  private JPanel contentPanel;
  private JLabel propertyNameLabel;
  private JLabel colorValueLabel;
  private JPanel colorPanel;

  public ColorRGBAComponent(ColorRGBA colorRGBA) {
    this(colorRGBA, null);
  }

  public ColorRGBAComponent(ColorRGBA colorRGBA, String propertyName) {
    super(colorRGBA, propertyName);
    $$$setupUI$$$();
    setComponent(colorRGBA);
  }

  @Override
  public void setComponent(ColorRGBA value) {
    if (value == null) {
      value = new ColorRGBA();
    }
    component = value;
    colorPanel.setBackground(ColorConverter.toColor(component));
    colorValueLabel.setText(String.format("[ %.2f, %.2f, %.2f, %.2f ]",
        component.r, component.g, component.b, component.a));

    colorPanel.repaint();
    colorPanel.revalidate();
    firePropertyChange(propertyName, null, component);
  }

  public void bind() {
    PropertyChangeListener propertyChangeListener = evt -> {
      setComponent(computeValue());
      firePropertyChange(propertyName, null, component);
    };
    colorPanel.addPropertyChangeListener(propertyChangeListener);
  }

  @Override
  public void setPropertyName(String propertyName) {
    super.setPropertyName(propertyName);
    propertyNameLabel.setText("ColorRGBA: " + propertyName);
  }

  private ColorRGBA computeValue() {
    return ColorConverter.toColorRGBA(colorPanel.getBackground());
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    contentPanel = new JPanel();
    contentPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
    colorPanel = new JPanel();
    colorPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    contentPanel.add(colorPanel,
        new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
            new Dimension(24, 24), new Dimension(24, 24), new Dimension(24, 24), 0, false));
    colorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null,
        TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    colorValueLabel = new JLabel();
    colorValueLabel.setText("Label");
    contentPanel.add(colorValueLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    propertyNameLabel = new JLabel();
    propertyNameLabel.setText("Label");
    contentPanel.add(propertyNameLabel,
        new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER,
            GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    nullButton = new JButton();
    nullButton.setText("null");
    contentPanel.add(nullButton,
        new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JSeparator separator1 = new JSeparator();
    contentPanel.add(separator1,
        new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null,
            null, 0, false));
  }

  /**
   *
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPanel;
  }

  private void createUIComponents() {
    contentPanel = this;

    colorPanel.addMouseListener(new MouseListener() {
      @Override
      public void mouseClicked(MouseEvent e) {

        Color color = JColorChooser.showDialog(null,
            "Color",
            colorPanel.getBackground());

        if (color == null) {
          return;
        }
        ColorRGBA newValue = ColorConverter.toColorRGBA(color);
        colorValueLabel.setText(String.format("[ %.2f, %.2f, %.2f, %.2f ]",
            newValue.r, newValue.g, newValue.b, newValue.a));
        setComponent(newValue);
      }

      @Override
      public void mousePressed(MouseEvent e) {

      }

      @Override
      public void mouseReleased(MouseEvent e) {

      }

      @Override
      public void mouseEntered(MouseEvent e) {

      }

      @Override
      public void mouseExited(MouseEvent e) {

      }
    });
  }
}
