package com.jayfella.devkit.properties.component;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import java.beans.PropertyChangeListener;
import javax.swing.*;
import java.awt.*;

public class IntegerComponent extends JMEDevKitComponentSwingView<Integer> {

    private JFormattedTextField valueTextField;
    private JPanel contentPanel;
    private JLabel propertyNameLabel;

    public IntegerComponent(Integer value) {
        this(value, null);
    }

    public IntegerComponent(Integer value, String propertyName) {
        super(value, propertyName);
        $$$setupUI$$$();
        setComponent(value);
    }

    @Override
    public void setComponent(Integer value) {
        if (value == null) {
            value = 0;
        }
        component = value;
        this.valueTextField.setValue(value);
    }

    public void bind() {
        PropertyChangeListener propertyChangeListener = evt -> {
            setComponent(computeValue());
            firePropertyChange(propertyName, null, component);
        };
        valueTextField.addPropertyChangeListener(propertyChangeListener);
    }

    @Override
    public void setPropertyName(String propertyName) {
        super.setPropertyName(propertyName);
        propertyNameLabel.setText("Vector3f: " + propertyName);
    }

    private Integer computeValue() {
        return ((Number) valueTextField.getValue()).intValue();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        propertyNameLabel = new JLabel();
        propertyNameLabel.setText("Integer");
        contentPanel.add(propertyNameLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        valueTextField = new JFormattedTextField();
        contentPanel.add(valueTextField, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JSeparator separator1 = new JSeparator();
        contentPanel.add(separator1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

    private void createUIComponents() {
        contentPanel = this;
        bind();
    }
}
