package com.jayfella.devkit.properties.component;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jme3.math.Vector2f;
import java.awt.Dimension;
import java.awt.Insets;
import java.beans.PropertyChangeListener;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

public class Vector2fComponent extends JMEDevKitComponentSwingView<Vector2f> {

  private JPanel contentPanel;
  private JLabel propertyNameLabel;
  private JFormattedTextField xTextField;
  private JFormattedTextField yTextField;
  private JButton nullButton;
  private JButton normalizeButton;
  private boolean nullable;

  public Vector2fComponent(boolean nullable) {
    this(null, null, true);
  }

  public Vector2fComponent(Vector2f vector2f) {
    this(vector2f, null);
  }

  public Vector2fComponent(Vector2f vector2f, String propertyName) {
    this(vector2f, propertyName, false);
  }

  public Vector2fComponent(Vector2f vector2f, String propertyName, boolean nullable) {
    super(vector2f, propertyName);
    $$$setupUI$$$();
    setValue(vector2f);
    this.nullable = nullable;
  }

  public void setValue(Vector2f value) {
    if (value != null) {
      this.xTextField.setValue(value.x);
      this.yTextField.setValue(value.y);
    } else {
      this.xTextField.setText("null");
      this.yTextField.setText("null");
    }
  }

  public void bind() {
    PropertyChangeListener propertyChangeListener = evt -> {
      saveViewValueToModel();
      firePropertyChange(propertyName, null, component);
    };
    xTextField.addPropertyChangeListener(propertyChangeListener);
    yTextField.addPropertyChangeListener(propertyChangeListener);
  }

  private void saveViewValueToModel() {
    setValue(getInputValue());
  }

  @Override
  public void setPropertyName(String propertyName) {
    super.setPropertyName(propertyName);
    propertyNameLabel.setText("Vector3f: " + propertyName);
  }

  private Vector2f getInputValue() {
    float x = ((Number) xTextField.getValue()).floatValue();
    float y = ((Number) yTextField.getValue()).floatValue();
    return new Vector2f(x, y);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    contentPanel = new JPanel();
    contentPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
    final JSeparator separator1 = new JSeparator();
    contentPanel.add(separator1,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null,
            null, 0, false));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
    contentPanel.add(panel1,
        new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
            null, 0, false));
    final JLabel label1 = new JLabel();
    label1.setText("x");
    panel1.add(label1,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
    final JLabel label2 = new JLabel();
    label2.setText("y");
    panel1.add(label2,
        new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
            false));
    xTextField = new JFormattedTextField();
    panel1.add(xTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST,
        GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    yTextField = new JFormattedTextField();
    panel1.add(yTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST,
        GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
    contentPanel.add(panel2,
        new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
            null, 0, false));
    propertyNameLabel = new JLabel();
    propertyNameLabel.setText("Vector2f");
    panel2.add(propertyNameLabel,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null,
            null, 0, false));
    normalizeButton = new JButton();
    normalizeButton.setText("normalize");
    panel2.add(normalizeButton,
        new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    nullButton = new JButton();
    nullButton.setText("null");
    panel2.add(nullButton,
        new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPanel;
  }


  private void createUIComponents() {
    contentPanel = this;

    xTextField = new JFormattedTextField();
    yTextField = new JFormattedTextField();

    normalizeButton = new JButton();

    normalizeButton.addActionListener(e -> {

      Vector2f value = getInputValue();

      if (value != null) {
        Vector2f normalized = value.normalize();
        // setValue(normalized);
        xTextField.setValue(normalized.x);
        yTextField.setValue(normalized.y);
      }

    });
    nullButton = new JButton();

    nullButton.setVisible(nullable);
    nullButton.addActionListener(e -> {
      if (nullable) {
        xTextField.setText("null");
        yTextField.setText("null");
      }
    });

    FloatFormatFactory floatFormatFactory = new FloatFormatFactory();

    xTextField.setFormatterFactory(floatFormatFactory);
    yTextField.setFormatterFactory(floatFormatFactory);
  }

}
