package fr.exratio.devkit.properties.component.colorgba;

import com.github.weisj.darklaf.listener.MouseClickListener;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jme3.math.ColorRGBA;
import fr.exratio.devkit.core.ColorConverter;
import fr.exratio.devkit.properties.component.AbstractPropertyEditor;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;

public class ColorRGBAEditor extends AbstractPropertyEditor<ColorRGBA> {

  public static final String LISTENED_PROPERTY_NAME = "background";

  private JPanel contentPanel;
  private JLabel colorValueLabel;
  private JPanel colorPanel;

  public ColorRGBAEditor() {
    this(new ColorRGBA());
  }

  public ColorRGBAEditor(ColorRGBA colorRGBA) {
    super(colorRGBA);
    if (colorRGBA == null) {
      value = new ColorRGBA();
    }
    $$$setupUI$$$();
  }

  @Override
  public void setTypedValue(ColorRGBA newValue) {
    if (newValue == null) {
      newValue = new ColorRGBA();
    }
    colorPanel.setBackground(ColorConverter.toColor(newValue));
    colorValueLabel.setText(String.format("[ %.2f, %.2f, %.2f, %.2f ]",
        newValue.r, newValue.g, newValue.b, newValue.a));
    colorPanel.repaint();
    colorPanel.revalidate();
    super.setTypedValue(newValue);
  }

  protected ColorRGBA computeValue() {
    return ColorConverter.toColorRGBA(colorPanel.getBackground());
  }

  @Override
  public Component getCustomEditor() {
    return contentPanel;
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    contentPanel = new JPanel();
    contentPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    contentPanel.add(colorPanel,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
            new Dimension(24, 24), new Dimension(24, 24), new Dimension(24, 24), 0, false));
    colorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null,
        TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    colorValueLabel = new JLabel();
    colorValueLabel.setText("Label");
    contentPanel.add(colorValueLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
        GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }


  public JComponent $$$getRootComponent$$$() {
    return contentPanel;
  }

  private void createUIComponents() {
    colorPanel = new JPanel();
    colorPanel.setBackground(ColorConverter.toColor(value));
    colorPanel.addMouseListener((MouseClickListener) e -> {

      Color color = JColorChooser.showDialog(null,
          "Color",
          colorPanel.getBackground());

      if (color == null) {
        return;
      }
      ColorRGBA newValue = ColorConverter.toColorRGBA(color);
      colorValueLabel.setText(String.format("[ %.2f, %.2f, %.2f, %.2f ]",
          newValue.r, newValue.g, newValue.b, newValue.a));
      setTypedValue(newValue);
    });
    colorPanel.addPropertyChangeListener(LISTENED_PROPERTY_NAME, propertyChangeListener);
  }

}
